apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: prinsoo/e-commerce:frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_PORT
              value: "5432"
      restartPolicy: Always
      volumes:
        - name: frontend-data
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort